# Generated by Django 6.0.5 on 2026-05-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laptop_name', models.CharField(max_length=30)),
                ('Laptop_desc', models.TextField()),
                ('Laptop_img', models.FileField(default=None, max_length=250, null=True, upload_to='img/')),
            ],
        ),
    ]
